#!/bin/sh
echo Waiting for USB mass storage
sleep 7

echo Trying to mount / on sdb2
umount /newroot
mount -t ext2 -o rw /dev/sdb2 /newroot && exec switch_root /newroot /linuxrc

echo Trying to mount internal/rootfs
mount -t vfat -o rw,sync /dev/sdb1 /mnt/ext
losetup /dev/loop0 /mnt/ext/rootfs
mount -t ext2 -o rw /dev/loop0 /newroot && exec switch_root /newroot /linuxrc
losetup -d /dev/loop0
umount /mnt/ext

echo Trying to mount card/rootfs
mount -t vfat -o rw,sync /dev/sda1 /mnt/card
losetup /dev/loop0 /mnt/card/rootfs
mount -t ext2 -o rw /dev/loop0 /newroot && exec switch_root /newroot /linuxrc
losetup -d /dev/loop0
umount /mnt/card

echo Failed.
